import Head from 'next/head'
import Link from 'next/link'
import { Form, Row, Col, Button } from 'react-bootstrap';
import styles from '../styles/Auth.module.scss'
import { IconFb, IconGoogle } from '../public/icons'

function Home() {
  return (
    <div className={styles.auth_container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content_left}>
        <div className={styles.content_logo}>
          <img className={styles.logo1} src='/img/logo-1.png' />
        </div>
        <img className={styles.logo2} src='/img/logo-2.png' />
      </div>
      <div className={styles.content_right}>
        <div className='card_auth'>
          <div className={styles.block_logo}>
            <img className={styles.block_logo_img} src='/img/logo-2.png' />
          </div>
          <Form.Group className='form-group'>
            <Form.Control type="text" placeholder="Ingrese su usuario" />
          </Form.Group>
          <Form.Group className='form-group'>
            <Form.Control type="text" placeholder="Contraseña" />
          </Form.Group>
          <Button>Iniciar Sesion</Button>
          <a href='#'>Olvidó su contraseña?</a>
          <div className='d-flex justify-content-around'>
            <button className='btn btn-social'><IconFb />Iniciar Sesión</button>
            <button className='btn btn-social'><IconGoogle />Iniciar Sesión</button>
          </div>
        </div>
        <p>¿No tiene cuenta? <Link href="/registro">Cree Cuenta</Link></p>
      </div>
    </div>
  )
}

export default Home;

Home.getLayout = function PageLayout(page) {
  return (
    <>
      {page}
    </>
  )
}