import Head from 'next/head'
import Link from 'next/link'
import { Form, Row, Col, Button } from 'react-bootstrap';
import styles from '../styles/Auth.module.scss'

function Registro() {
  return (
    <div className={styles.auth_container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content_left}>
        <div className={styles.content_logo}>
          <img className={styles.logo1} src='/img/logo-1.png' />
        </div>
        <img className={styles.logo2} src='/img/logo-2.png' />
      </div>
      <div className={styles.content_right}>
        <div className='card_auth'>
          <div className={styles.block_logo}>
            <img className={styles.block_logo_img} src='/img/logo-2.png' />
          </div>
          <h4 className={styles.title}>Crear Cuenta</h4>
          <Form.Group className='form-group'>
            <Form.Control type="text" placeholder="Nombre completo" />
          </Form.Group>
          <Form.Group className='form-group'>
            <Form.Control type="text" placeholder="Correo Electrónico" />
          </Form.Group>
          <Row className='form-row'>
            <Col>
              <Form.Group className='form-group'>
                <Form.Select>
                  <option>Tipo Documento</option>
                </Form.Select>
              </Form.Group>
            </Col>
            <Col>
              <Form.Group className='form-group'>
                <Form.Control type="text" placeholder="N° Documento" />
              </Form.Group>
            </Col>
          </Row>
          <Form.Group className='form-group'>
            <Form.Select>
              <option>Sede</option>
            </Form.Select>
          </Form.Group>
          <Button>Registrarse</Button>
        </div>
        <p>Ya tiene una cuenta? <Link href="/">Login</Link></p>
      </div>
    </div>
  )
}

export default Registro;

Registro.getLayout = function PageLayout(page) {
  return (
    <>
      {page}
    </>
  )
}